#!/usr/bin/env bash

command -v opencv_traincascade > /dev/null 2 >& 1 && command -v opencv_createsamples > /dev/null 2 >& 1 || {
    echo 'OpenCV is either not installed, or the utilities are not on your path. OpenCV can be downloaded from https://opencv.org/downloads.html.'
}

if [[ -f 'fg.vec' ]]
then
    while [ true ]
    do
        read -p 'Files detected. Do you wish to clean and regenerate them? [y/n] ' ans
        case $ans in
            [Yy]* ) ./clean; ./topng; ./resize; ./list; ./vec; ./merge; ./train; break ;;
            [Nn]* ) break; ./train ;;
            *) echo 'Please enter [y/n].' ;;
        esac
    done
else
    ./topng; ./resize; ./list; ./vec; ./merge; ./train
fi
