#!/usr/bin/env bash

for f in $(ls positive/*.png | grep '^[resize_]*')
do
  convert $f -resize x256 positive/$(basename f) 
done

for f in $(ls negative/*.png | grep '^[resize_]*')
do
  convert $f -resize x256 negative/$(basename f)
done
