#!/usr/bin/env bash

# convert jpgs in positive/ to pngs
for f in $(ls {positive/*.jpg,negative/*.jpg}) 
do
  filename=$(basename "$f")
  extension="${filename##*.}"
  filename="${filename%.*}"
  convert $f $(dirname $f)/$filename.png
done
